export const items = [
  {
    id: Math.random(),
    title: "وجبه فول مصري",
    description: "وصف الفطار",
    price: "100 جنيه",
    category: "فطار",
    imgUrl: "1.png",
  },
  {
    id: Math.random(),
    title: "وجبه غدا",
    description: "وصف الفطار",
    price: "80 جنيه",
    category: "غدا",
    imgUrl: "2.png",
  },
  {
    id: Math.random(),
    title: "وجبه ارز بليل مصري",
    description: "وصف الحلويات",
    price: "120 جنيه",
    category: "حلويات",
    imgUrl: "3.png",
  },
  {
    id: Math.random(),
    title: "وجبه عشاء",
    description: "وصف العشاء",
    price: "40 جنيه",
    category: "عشاء",
    imgUrl: "3.png",
  },
  {
    id: Math.random(),
    title: "وجبه غدا ممتاز",
    description: "وصف الفطار",
    price: "30 جنيه",
    category: "غدا",
    imgUrl: "2.png",
  },
  {
    id: Math.random(),
    title: "وجبه عشاء درجه اولى",
    description: "وصف الفطار",
    price: "50 جنيه",
    category: "عشاء",
    imgUrl: "1.png",
  },
  {
    id: Math.random(),
    title: "وجبه حلويات",
    description: "وصف الحلويات",
    price: "80 جنيه",
    category: "حلويات",
    imgUrl: "3.png",
  },
  {
    id: Math.random(),
    title: " وجبه حلويات ممتازه",
    description: "وصف الحلويات",
    price: "100 جنيه",
    category: "حلويات",
    imgUrl: "3.png",
  },
];
